# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-16.04"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  
  
    # postrges
    config.vm.network "forwarded_port", guest: 5432, host: 5432
  
    config.vm.network "private_network", ip: "192.168.33.99"
  
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end
  end
  